part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();

  static const SPLASH = _Paths.SPLASH;
  static const LOGIN = _Paths.LOGIN;
  static const SIGNUP = _Paths.SIGNUP;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const RESET_PASSWORD = _Paths.RESET_PASSWORD;
  static const DASHBOARD_VIEW = _Paths.DASHBOARD_VIEW;
  static const VERIFY_OTP = _Paths.VERIFY_OTP;
  static const SUCCESS = _Paths.SUCCESS;
  static const PAGE = _Paths.PAGE;
  static const ACCOUNT_SETUP = _Paths.ACCOUNT_SETUP;
  static const VET_ACCOUNT_SETUP = _Paths.VET_ACCOUNT_SETUP;
  static const PET_TYPE = _Paths.PET_TYPE;
  static const PET_INFO = _Paths.PET_INFO;
  static const SUBSCRIPTION = _Paths.SUBSCRIPTION;
  static const OTHER_VET = _Paths.OTHER_VET;
  static const VET_SEARCH = _Paths.VET_SEARCH;
  static const VET_PROFILE = _Paths.VET_PROFILE;
  static const MY_APPOINTMENT = _Paths.MY_APPOINTMENT;
  static const APPOINTMENT_DETAIL = _Paths.APPOINTMENT_DETAIL;
  static const FILTER = _Paths.FILTER;
  static const SETTING = _Paths.SETTING;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const DELETE_ACCOUNT = _Paths.DELETE_ACCOUNT;
  static const MANAGE_SUBSCRIPTION = _Paths.MANAGE_SUBSCRIPTION;
  static const PROFILE = _Paths.PROFILE;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const SCHEDULE_APPOINTMENT = _Paths.SCHEDULE_APPOINTMENT;
  static const MEDICAL_RECORD = _Paths.MEDICAL_RECORD;
  static const ADD_PET = _Paths.ADD_PET;
  static const PET_MORE_INFO = _Paths.PET_MORE_INFO;
  static const ADDRESSES = _Paths.ADDRESSES;
  static const ADD_LOCATION_PCIKER = _Paths.ADD_LOCATION_PCIKER;
  static const PAYMENT_DETAIL = _Paths.PAYMENT_DETAIL;
  static const PAYMENT_MANAGEMENT = _Paths.PAYMENT_MANAGEMENT;
  static const CANCEL_APPOINTMENT = _Paths.CANCEL_APPOINTMENT;
  static const VET_APPOINTMENT_DETAIL = _Paths.VET_APPOINTMENT_DETAIL;
  static const CHAT = _Paths.CHAT;
  static const CHAT_ROOM = _Paths.CHAT_ROOM;
  static const IMAGE_VIEW = _Paths.IMAGE_VIEW;
  static const VIDEO_VIEW = _Paths.VIDEO_VIEW;
  static const APPOINTMENT_HISTORY = _Paths.APPOINTMENT_HISTORY;
  static const VET_APPOINTMENT_HISTORY = _Paths.VET_APPOINTMENT_HISTORY;
  static const SEARCH = _Paths.SEARCH;
  static const MANAGE_TIME_SLOT = _Paths.MANAGE_TIME_SLOT;
  static const ADD_TIME_SLOT = _Paths.ADD_TIME_SLOT;
  static const VET_MY_PROFILE = _Paths.VET_MY_PROFILE;
  static const VET_EDIT_PROFILE = _Paths.VET_EDIT_PROFILE;
  static const STATISTICS = _Paths.STATISTICS;
  static const STATISTIC_DETAIL = _Paths.STATISTIC_DETAIL;
  static const PRESCRIBE_MEDICINE = _Paths.PRESCRIBE_MEDICINE;
  static const VIDEO_CALL = _Paths.VIDEO_CALL;
  static const EDIT_SLOT = _Paths.EDIT_SLOT;
  static const CONTACT_US = _Paths.CONTACT_US;
}

abstract class _Paths {
  _Paths._();

  static const SPLASH = '/splash';
  static const LOGIN = '/login';
  static const SIGNUP = '/sign_up';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const RESET_PASSWORD = '/reset-password';
  static const VERIFY_OTP = '/verify-otp';
  static const SUCCESS = '/success';
  static const DASHBOARD_VIEW = '/dashboardView';
  static const PAGE = '/page';
  static const ACCOUNT_SETUP = '/account_setup';
  static const VET_ACCOUNT_SETUP = '/vet_account_setup';
  static const PET_TYPE = '/pet_type';
  static const PET_INFO = '/pet_info';
  static const SUBSCRIPTION = '/subscription';
  static const OTHER_VET = '/other_vet';
  static const VET_SEARCH = '/vet_search';
  static const VET_PROFILE = '/vet_profile';
  static const MY_APPOINTMENT = '/my_appointment';
  static const APPOINTMENT_DETAIL = '/appointment_detail';
  static const FILTER = '/filter';
  static const SETTING = '/setting';
  static const CHANGE_PASSWORD = '/change_password';
  static const DELETE_ACCOUNT = '/delete_account';
  static const MANAGE_SUBSCRIPTION = '/manage_subscription';
  static const PROFILE = '/profile';
  static const EDIT_PROFILE = '/edit_profile';
  static const NOTIFICATION = '/notification';
  static const SCHEDULE_APPOINTMENT = '/schedule_appointment';
  static const MEDICAL_RECORD = '/medical_record';
  static const ADD_PET = '/add_pet';
  static const PET_MORE_INFO = '/pet_more_info';
  static const ADDRESSES = '/addresses';
  static const ADD_LOCATION_PCIKER = '/add_location_picker';
  static const PAYMENT_DETAIL = '/payment_detail';
  static const CANCEL_APPOINTMENT = '/cancel_appointment';
  static const VET_APPOINTMENT_DETAIL = '/vet_appointment_detail';
  static const CHAT = '/chat';
  static const CHAT_ROOM = '/chat_room';
  static const IMAGE_VIEW = '/image_view';
  static const VIDEO_VIEW = '/video_view';
  static const APPOINTMENT_HISTORY = '/appointment_history';
  static const VET_APPOINTMENT_HISTORY = '/vet_appointment_history';
  static const SEARCH = '/search';
  static const MANAGE_TIME_SLOT = '/manage_time_slot';
  static const ADD_TIME_SLOT = '/add_time_slot';
  static const VET_MY_PROFILE = '/vet_my_profile';
  static const VET_EDIT_PROFILE = '/vet_edit_profile';
  static const PAYMENT_MANAGEMENT = '/payment_management';
  static const STATISTICS = '/statistics';
  static const STATISTIC_DETAIL = '/statistic_detail';
  static const PRESCRIBE_MEDICINE = '/prescribe_medicine';
  static const VIDEO_CALL = '/video_call';
  static const EDIT_SLOT = '/edit_slot';
  static const CONTACT_US = '/contact_us';

}
